server:
  port: 8086
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

sms:
  smsServerUrl: https://javayong.cn/smsadmin
  appKey: qQjEiFzn80v8VM4h
  appSecret: 9c465ece4bd26a9be77f3d0e2606bd